import { createMiddleware } from "@solidjs/start/middleware";
import { retiredCityRedirect } from "~/lib/slug";

/**
 * robots.txt and the sitemaps are generated by the backend from the database
 * and refreshed when content is published in the admin, so they are proxied
 * from the API host rather than built here.
 *
 * This used to be a Vercel rewrite (vercel.json / the Vercel block in
 * app.config.ts). The Cloudflare Pages preset honours neither, and Pages'
 * _redirects cannot proxy to another origin, so it lives in the middleware,
 * which runs on every preset. Without it these paths fall through to the
 * [stream] route and come back as an HTML page.
 */
const SITEMAP_ORIGIN = "https://api.edu.aajneeti.social";
const SITEMAP_PATH = /^\/(?:robots\.txt|sitemap(?:-[^/]+)?\.xml)$/;

// fetch() has already decoded the body, so the upstream's encoding and length
// no longer describe what we send; the platform recomputes both.
const DROPPED_HEADERS = ["content-encoding", "content-length", "transfer-encoding", "connection"];

async function proxySitemap(request: Request, url: URL): Promise<Response> {
  const method = request.method === "HEAD" ? "HEAD" : "GET";
  const upstream = await fetch(SITEMAP_ORIGIN + url.pathname + url.search, { method });
  const headers = new Headers(upstream.headers);
  for (const h of DROPPED_HEADERS) headers.delete(h);
  return new Response(method === "HEAD" ? null : upstream.body, {
    status: upstream.status,
    headers,
  });
}

/**
 * Server middleware. Runs ahead of routing, so a response here is a real
 * response rather than a client-side navigation.
 *
 * It proxies robots.txt and the sitemaps (above), and collapses the city slugs
 * retired by the backend's duplicate-city merge (see RETIRED_CITY_SLUGS) onto
 * the city that absorbed them, with a 301 so the ranking those URLs already
 * hold transfers instead of being dropped. Everything else falls through
 * untouched.
 */
export default createMiddleware({
  onRequest(event) {
    const url = new URL(event.request.url);
    if (SITEMAP_PATH.test(url.pathname)) return proxySitemap(event.request, url);
    const to = retiredCityRedirect(url.pathname);
    if (!to) return;
    return new Response(null, {
      status: 301,
      headers: { Location: to + url.search },
    });
  },
});
